version: '3'
services:
  idp:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    command:
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=singleFile"
      - "-Dkeycloak.migration.file=/tmp/config.json"
      - "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
    volumes:
      - ./idp-data:/opt/jboss/keycloak/standalone/data
      - ./config.json:/tmp/config.json
    ports:
      - "8080:8080"
    networks:
      - public_net


networks:
  public_net:
    external: true
