version: '3'
services:
  app-legacy:
    image: my-express-app
    ports:
      - "3000:3000"
    networks:
      - private_net

  # nginx-proxy:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - "80:80"
  #   networks:
  #     - app-network
  #   depends_on:
  #     - express-app
  
  proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy
    volumes:
      - ../proxy/oauth2-proxy.cfg:/etc/oauth2-proxy.cfg
    command:
      - --config
      - /etc/oauth2-proxy.cfg
    ports:
      - "4180:4180"
    networks:
      - public_net
      - private_net
    depends_on:
      - app-legacy

  # keycloak:
  #   image: jboss/keycloak
  #   environment:
  #     KEYCLOAK_USER: admin
  #     KEYCLOAK_PASSWORD: admin
  #   command:
  #     - "-Dkeycloak.migration.action=import"
  #     - "-Dkeycloak.migration.provider=singleFile"
  #     - "-Dkeycloak.migration.file=/tmp/config.json"
  #     - "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
  #   volumes:
  #     - ../idp/config.json:/tmp/config.json
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - app-network

  # Keycloak service configuration goes here

networks:
  public_net:
    external: true
  private_net:
    external: true